name: CI on Pull Request

on: [pull_request]

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.7 for awscli
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install awscli
        run: pip install --upgrade pip awscli
      - name: Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_REGISTRY_URL: 104420014930.dkr.ecr.ap-northeast-1.amazonaws.com/tapyrus-core
        run: |
          # aws login
          eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
          # docker
          export BUILD_ID=COMMIT_$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t ${AWS_REGISTRY_URL}:$BUILD_ID .
          if [ $AWS_ACCESS_KEY_ID ]; then docker push ${AWS_REGISTRY_URL}:$BUILD_ID; fi

  arm:
    name: "[PENDING]ARM"
    runs-on: ubuntu-18.04
    steps:
      - run: echo "PENDING. make install is failing."
#      - uses: actions/checkout@v1
#      - run: |
#          source ./default-env.sh
#          HOST=arm-linux-gnueabihf \
#          PACKAGES="g++-arm-linux-gnueabihf" \
#          DEP_OPTS="NO_QT=1" \
#          GOAL="install" \
#          BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports" \
#          bash -xe ./build-test.sh

  win32:
    name: "[PENDING]WIN32"
    runs-on: ubuntu-18.04
    steps:
      - run: echo "PENDING. Unit test execution is failing."
#      - uses: actions/checkout@v1
#      - run: |
#          source ./default-env.sh
#          HOST=i686-w64-mingw32 \
#          DPKG_ADD_ARCH="i386" \
#          DEP_OPTS="NO_QT=1" \
#          PACKAGES="python3 nsis g++-mingw-w64-i686 wine-binfmt wine32" \
#          RUN_TESTS=true \
#          GOAL="install" \
#          BITCOIN_CONFIG="--enable-reduce-exports" \
#          bash -xe ./build-test.sh

  win64:
    name: "[PENDING]WIN64"
    runs-on: ubuntu-18.04
    steps:
      - run: echo "PENDING. Unit test execution is failing."
      - uses: actions/checkout@v1
      - run: |
          source ./default-env.sh
          HOST=x86_64-w64-mingw32 \
          DEP_OPTS="NO_QT=1" \
          PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine-binfmt wine64" \
          RUN_TESTS=true \
          GOAL="install" \
          BITCOIN_CONFIG="--enable-reduce-exports" \
          bash -xe ./build-test.sh

  linux-32bit-dash:
    name: "[PENDING]32-bit + dash"
    runs-on: ubuntu-18.04
    steps:
      - run: echo "PENDING. Runnning time is over 2 hours limit."
#      - uses: actions/checkout@v1
#      - run: |
#          source ./default-env.sh
#          HOST=i686-pc-linux-gnu \
#          PACKAGES="g++-multilib python3-zmq" \
#          DEP_OPTS="NO_QT=1" \
#          RUN_TESTS=true \
#          GOAL="install" \
#          BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" \
#          CONFIG_SHELL="/bin/dash" \
#          bash -xe ./build-test.sh

  linux-with-qt:
    name: "[PENDING]x86_64 Linux (uses qt5 dev package instead of depends Qt to speed up build and avoid timeout)"
    runs-on: ubuntu-18.04
    steps:
      - run: echo "PENDING. GUI unit tests are failing."
#      - uses: actions/checkout@v1
#      - run: |
#          source ./default-env.sh
#          HOST=x86_64-unknown-linux-gnu \
#          PACKAGES="python3-zmq qtbase5-dev qttools5-dev-tools protobuf-compiler libdbus-1-dev libharfbuzz-dev libprotobuf-dev" \
#          DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1 ALLOW_HOST_PACKAGES=1" \
#          RUN_TESTS=true \
#          RUN_BENCH=true \
#          GOAL="install" \
#          BITCOIN_CONFIG="--enable-zmq --with-gui=qt5 --enable-glibc-back-compat --enable-reduce-exports --enable-debug" \
#          CXXFLAGS="-g0 -O2" \
#          bash -xe ./build-test.sh

  linux-with-qt-and-system-lib:
    name: "[PENDING]x86_64 Linux (Qt5 & system libs)"
    runs-on: ubuntu-18.04
    steps:
      - run: echo "PENDING. GUI unit tests are failing."
#      - uses: actions/checkout@v1
#      - run: |
#          source ./default-env.sh
#          HOST=x86_64-unknown-linux-gnu
#          PACKAGES="python3-zmq qtbase5-dev qttools5-dev-tools libssl1.0-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libdb5.3++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev"
#          NO_DEPENDS=1
#          RUN_TESTS=true
#          GOAL="install"
#          BITCOIN_CONFIG="--enable-zmq --with-incompatible-bdb --enable-glibc-back-compat --enable-reduce-exports --with-gui=qt5 CPPFLAGS=-DDEBUG_LOCKORDER"
#          bash -xe ./build-test.sh

  linux-no-wallet:
    name: "[PENDING]x86_64 Linux, No wallet"
    runs-on: ubuntu-18.04
    steps:
      - run: echo "PENDING. GUI unit tests are failing."
#      - uses: actions/checkout@v1
#      - run: |
#          source ./default-env.sh
#          HOST=x86_64-unknown-linux-gnu
#          PACKAGES="python3"
#          DEP_OPTS="NO_WALLET=1"
#          RUN_TESTS=true
#          GOAL="install"
#          BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
#          bash -xe ./build-test.sh

  cross-mac:
    name: Cross Mac
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          source ./default-env.sh
          HOST=x86_64-apple-darwin14 \
          PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev python3-setuptools-git" \
          OSX_SDK=10.11 \
          GOAL="all deploy" \
          BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --enable-werror" \
          bash -xe ./build-test.sh
